export default {
  '502': '502 Bad Gateway',
  '404': '404 Not Found',
  '0': '成功',
  '1': '失败',
  'REQUEST_ERROR': '请求错误', //4001
  'METHOD_ERROR': '方法错误', //4002
  'PARAMETER_ERROR': '参数错误', //4003
  'VALIDATION_ERROR': '验证错误', //4004
  'TOKEN_ERROR': '令牌错误', //4005
  'INTERNAL_ERROR': '内部错误', //4000
  'SERVICE_BUSY': '服务繁忙', //4009
  'INFO_NULL': '信息不存在', //4010
  'SESSIONID_INVALID': '登录态失效', //4101
  'USERNAME_ERROR': '用户名错误', //4102
  'PASSWORD_ERROR': '密码错误', //4103
  'PASSWORD_UNSET': '密码未设置', //4106
  'ACCOUNT_NULL': '账号不存在', //4107
  'ACCOUNT_EXISTED': '账号已存在', //4108
  'ACCOUNT_BLOCKED': '账号被封禁', //4109
  'CHECKCODE_ERROR': '验证码错误',
  'NO_PERMISSION': '无权限访问', //4120
  'PRODUCT_ONLINE': '商品已是上线状态',
  'BRAND_INEXISTENCE': '品牌未上线',
  'COMPANY_NULL': '无子公司',
  'BANNERID_ERROR': '删除失败',
  'PRODUCT_MUST_ONLINE': '添加失败,请检查是否已添加',
  'COST_NULL': '商品无进货价格',
  'USER_NULL': '用户未注册',
  'MANAGER_EXISTED': '该店铺已有店长',
  'ACCOUNT_BOUND': '该账户已存在',
  'TIME_OUT': '仅能删除一天内添加的数据',
  'IS_KEEPER': '已存在此管理员',
  'IS_SALESMAN': '已为店长或店员',
  'PRODUCT_OFFLINE': '商品为下线状态',
  'ACTIVITY_OFFLINE': '活动为下线状态',
  'NOT_EDITING': '上线过的活动无法删除',
  'COUPON_ONLINE': '上线过的优惠券无法删除',
  'PRODUCT_EXISTED': '该商品已在首页模块中',
  'EXISTED': '该品牌或商品已有活动',
  'DELETE_ERROR': '删除失败,上线过的商品无法删除',
  'BARCODE_EXISTED': '条形码已存在',
  'MORE_THAN_YEAR': '活动时间不允许超过一年',
  'IS_DEFAULT': '默认价格商品无法下线',
  'COMMAND_NOT_EXISTED': '指令不存在',
  'TOTAL_LIMITED': '一天只能提交一次',
  'REQUEST_ERROR': '请求错误',
  'SCORE_NOT_ENOUGH': '积分不足',
  'STOCK_EMPTY': '此奖品已领完',
  'TODAY_EXCHANGED': '今天已兑换，请明天再来',
  'VALIDATION_ERROR': '验证错误',
  'PRICE_NULL': '价格为空',
  'ZM_ORDERID_ERROR': '芝麻订单号为空',
  'COUPON EXPIRED': '优惠劵已过期',
  'ORDERID_ERROR': '订单ID错误',
  'ORDER_NULL': '订单为空',
  'FORBIDDEN': '禁止访问',
  'ORDER_STATUS_ERROR': '订单状态错误',
  'ORDER_NOT_END': '订单未结束',
  'REFUNDING': '订单归还中',
  'BUYOUTED': '订单已买断',
  'BUYOUT_COST_ERROR': '订单买断金额错误',
  'BUYOUT_ERROR': '支付失败',

  'CODE_ERROR': '优惠码错误',
  'TOKEN_ERROR': 'TOKEN不能为空',
  'TOKEN_EXPIRED': 'TOKEN已失效',
  'ACCOUNT_NULL': '账户不存在',
  'ACCOUNT_BLOCKED': '账户被拉入黑名单',
  'OAUTH_ACCESS_TOKEN_FAILED': '获取支付宝授权信息失败',
  'ACCOUNT_BOUND': '账户已绑定其他支付宝',
  'ACCOUNT_EXISTED': '存在多个账户',
  'ORDER_CODE_EXPIRED': '优惠码不存在',
  'USERNAME_BOUND': '该手机号已绑定其他支付宝',
  'MSGCODE_ERROR': '验证码错误',
  'OCR_ERROR': '识别错误',
  'REALNAME_NOT_NULL': '真实姓名不能为空',
  'IDCARDNO_NOT_NULL': '身份证号码不能为空',
  'IDCARDNO_ERROR': '身份证号码格式错误',
  'IDCARDFRONT_NOT_NULL': '身份证正面照不能为空',
  'IDCARDBACK_NOT_NULL': '身份证反面照不能为空',
  'FACEIMG_NOT_NULL': '手持身份证图片不能为空',
  'LINKMAN_NOT_NULL': '联系人不能为空',
  'LINKTEL_NOT_NULL': '联系人电话不能为空',
  'LINKTEL_ERROR': '联系人电话格式错误',
  'PROVINCE_ERROR': '省份不能为空',
  'CITY_ERROR': '城市不能为空',
  'COUNTY_ERROR': '区/县不能为空',
  'TOWN_ERROR': '乡镇不能为空',
  'PLACE_ERROR': '详细地址不能为空',
  'IMAGE_PARSE_ERROR': '图片转化错误',
  'IMAGE_FACE_ERROR': '身份证正面识别错误',
  'REALNAME_ERROR': '真实姓名不对应',
  'IDCARDNO_ERROR': '身份证号码不对应',
  'IMAGE_BACK_ERROR': '身份证反面识别错误',
  'UPDATE_ERROR': '更新信息错误',
  'INSERT_ERROR': '新增信息错误',
  'FACE_ERROR': '身份证正面图片错误',
  'FACE_REALNAME_ERROR': '身份证姓名错误',
  'FACE_IDCARDNO_ERROR': '身份证号码错误',
  'BACK_ERROR': '身份证反面图片错误',
  'OVERTIME':'订单已超时，不能进行取消',


  'UNAUTHORIZED' : '跳到实名认证界面',
  'PRODUCTID_ERROR': 'PRODUCTID不能为空',
  'PRICEID_ERROR' :'PRICEID不能为空',
  'GUARANTEE_ERROR' :'担保方式不能为空',
  'MONTHS_ERROR': '租期不能为空',
  'PRODUCT_NULL': '找不到商品信息',
  'PRODUCT_OFFLINE': '商品已下线',
  'CALC_ERROR': '计算错误',
  'REPAYMENT_ERROR':'还款方式不能为空',
  'PICKTYPE_ERROR':'取货方式不能为空',
  'COUPON_NULL' : '找不到优惠券信息',
  'COUPON_EXPIRED':'优惠券已经过期',
  'COUPON_ERROR' :'优惠券已被使用',
  'SHOPID_ERROR' :'找不到店铺',
  'SHOP_NULL' :'找不到店铺信息',
  'SALESMANID_ERROR' : '找不到销售员',
  'SALESMAN_NULL' :'找不到销售员信息',
  'ADDRESS_INFO_NULL' :'地址信息为空',
  'ADDRESS_ERROR': 'addressid 不能为空',
  'STORE_NULL': '找不到仓库',
  'KEEPRER_NULL': '找不到仓库管理员',
  'KEEPER_ERROR' :'仓库管理员信息错误',
  'ORDER_COST_INSERT_ERROR': '新增计算结果错误',
  'ORC_TOTAL_LIMIT':'识别次数已受限',
  '02':'实名认证失败',
  'IDCARD_ERROR':'身份证号码错误',
  'USERNAME_ERROR':'店长手机号码只能填写此账号绑定的手机号码',
  'HAS_APPLIED':'已经申请，不能重复申请',
  'ACCOUNT_ACTIVATED': '已存在其他身份',

  'BIZTYPE_ERROR': '业务类型错误',
  'TEL_ERROR': '手机号码错误',
  'CHECKCODE_ERROR': '图片验证码错误',
  'MSGCODE_LIMIT': '今日发送次数已用完',
  'MSGCODE_UNUSED': '验证码未使用',
  'MSGCODE_FAILED': '验证码发送失败',
  'IMAGEID_ERROR': 'imageid不能为空',
  'ICON_X_ERROR': 'X不能为空',
  'ICON_Y_ERROR': 'Y不能为空',
  'CAPTCHA_ERROR': '验证失败，重新请求图片',
  'CAPTCHA_RETRY': '验证失败，请重试',
  'ORDER_TOKEN_ERROR': '此订单已失效，请重新下单',
  'CHECK_NOPASS':'实名认证不通过',
  'REASON_ERROR':'拒绝原因错误'
  
}